services:
  - type: web
    name: educatec
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: node servidor.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
